### ISSUE TITLE
Exception in merge_according_to (Utils.py) - line 136

### ISSUE THREAD

**Issue by marcrepo** [ilya-kolchinsky/OpenCEP#44]
The following simple pattern throws the exception on line 136 in merge_according_to function (Utils.py).

pattern = Pattern(
        SeqOperator(
            PrimitiveEventStructure("blue", "a"), 
            KleeneClosureOperator(PrimitiveEventStructure("red", "b"))
        ),
        TrueCondition(),
        timedelta(minutes=5)
    )

The input is the following (I am leaving out timestamps for clarity):
blue,1
blue,2 
red,1
red,2
red,3

Note that the exception is not thrown if I change SeqOperator to AndOperator but I believe SeqOperator should work as it follows the example in the OpenCEP documentation (shown below):

pattern = Pattern(
        SeqOperator(
            PrimitiveEventStructure("GOOG", "a"), 
            KleeneClosureOperator(PrimitiveEventStructure("GOOG", "b"))
        ),
        AndCondition(
            SmallerThanCondition(Variable("a", lambda x: x["Peak Price"]), Variable("b", lambda x: x["Peak Price"])),
            SmallerThanCondition(Variable("b", lambda x: x["Peak Price"]), Variable("c", lambda x: x["Peak Price"]))
        ),
        timedelta(minutes=5)
    )

Any suggestions or is this a bug?  Thanks.

**Comment by ilya-kolchinsky** [comment]
Thanks for pointing that out - it definitely looks like a bug. We will look into it asap.

**Comment by ilya-kolchinsky** [comment]
The bug was fixed.
